version: '3'
services:
  # Node.js application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - maria-db
    ports:
      - "4000:4000"
    restart: unless-stopped # Restart the container unless explicitly stopped
    networks:
      - book-explorer

  # MariaDB database
  maria-db:
    image: mariadb:latest
    container_name: maria-db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: SJFHFIHJGH673
      MYSQL_DATABASE: book_explorer
    ports:
      - "3306:3306"
    networks:
      - book-explorer

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - maria-db
    ports:
      - "3000:3000" # Map the frontend application's port to a host port of your choice
    restart: unless-stopped
    networks:
      - book-explorer

networks:
  book-explorer:
    driver: bridge