version: '3'
services:
  # Node.js application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:local
    container_name: backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - maria-db
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - bookolog

  # MariaDB database
  maria-db:
    image: mariadb:latest
    container_name: maria-db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: SJFHFIHJGH673
      MYSQL_DATABASE: bookolog
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - bookolog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    image: frontend:local
    container_name: frontend
    environment:
      - APP_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXTAUTH_SECRET=sdfsdfdsfsdf3234sfsdfg
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    depends_on:
      - backend
    links:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - bookolog

networks:
  bookolog:
    driver: bridge

volumes:
  mariadb_data:    