name: BuildAndPushImageOnHarbor

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        registry: reg.bookolog.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build Frontend Image
      run: |
        docker-compose build frontend

    - name: Build Backend Image
      run: |
        docker-compose build backend

    - name: Show All Images
      run: |
        docker images
 
    - name: Push Frontend
      run: |
        docker tag frontend:local reg.bookolog.com/bookolog/frontend
        docker push reg.bookolog.com/bookolog/frontend
    
    - name: Push Backend
      run: |
        docker tag backend:local reg.bookolog.com/bookolog/backend
        docker push reg.bookolog.com/bookolog/backend  
