name: Run Unit Tests

on:
  push:
    branches: [ "master", "development" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: root_test
          MARIADB_DATABASE: testdatabase
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DB_HOST: mariadb
      DB_USER: root
      DB_NAME: testdatabase
      DB_PASSWORD: root_test
      APP_ENV: development
      DB_DIALECT: mysql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up environment variables
        run: |
          echo "DB_HOST=${{ env.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_USER=${{ env.DB_USER }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ env.DB_NAME }}" >> $GITHUB_ENV
          echo "APP_ENV=${{ env.APP_ENV }}" >> $GITHUB_ENV
          echo "DB_DIALECT=${{ env.DB_DIALECT }}" >> $GITHUB_ENV    

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run database migrations
        working-directory: ./backend
        run: npm run migrate

      - name: Run Jest tests
        working-directory: ./backend
        run: npm test